#### 1.导入numpy库并简写为np 
(提示: import … as …)

In [1]:
import numpy as np

#### 2.打印numpy的版本及配置说明
(提示: np.__version__, np.show_config)

In [13]:
print(np.version.version)
print(np.__version__)

1.16.4
1.16.4


In [14]:
print(np.show_config())

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/Anaconda3\\Library\\include']
blas_op

#### 3.创建一个长度为10的空向量
(提示: np.zeros)

In [18]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.如何找到任何一数组的内存大小?
(提示:size, itemsize)

In [19]:
print(arr.itemsize)

8


#### 5. 如何从命令中找到numpy的add函数的说明文档 (提示np.info)

In [20]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 6. 创建一个长度为10并且除了第五个值为1的空向量

In [21]:
arr2 = np.zeros(10)
arr2[4] = 1
print(arr2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. 创建一个值域范围从10到49的向量
(提示:np.arange)

In [23]:
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.反转一个向量(从头开始依次进行反转) 
(提示array[::-1])

In [24]:
print(vector[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. 创建一个3x3并且值从0到8的矩阵
(提示 reshape)

In [26]:
arr3 = np.arange(9).reshape((3,3))
print(arr3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. 创建一个 10x10 的随机数组并找到它的最大值和最小值
(提示: min, max)

In [27]:
arr4 = np.random.randn(10,10)
print(np.min(arr4))
print(np.max(arr4))

-2.03207805866504
2.145676598551472


#### 11.  创建一个长度为30的随机向量并找到它的平均值
(提示: mean)

In [30]:
vec = np.random.randn(30)
print(np.mean(vec))
print(vec.mean())

0.0266742277680738
0.0266742277680738


#### 12. 对一个5x5的随机矩阵做归一化
(提示: (x-min)/(max - min)

In [31]:
arr5 = np.random.randn(5,5)
amax, amin = arr5.max(), arr5.min()
print((arr5 - amin)/amax - amin)

[[5.89834394 3.97102479 5.65539185 4.65430894 6.34142608]
 [4.27774443 5.11103014 4.47448238 4.59247818 3.76057375]
 [2.63363229 6.07133346 5.93689266 5.13707326 4.84772897]
 [4.92317609 4.96548839 4.87805865 4.08087376 4.04044826]
 [4.65649883 6.34190082 5.75450194 6.16712042 4.63817283]]


#### 13. 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？
(提示 np.dot)

In [32]:
a1 = np.random.randn(5,3)
b1 = np.random.randn(3,2)
print(np.dot(a1,b1))

[[ 0.282867   -0.22882336]
 [ 0.93412611 -0.41554336]
 [ 0.37082063 -0.05533658]
 [-0.58801761  0.35953362]
 [ 2.86912752 -0.9895118 ]]


#### 14. 在给定标量时, 如何找到数组中最接近标量的值?
(提示:argmin)

In [34]:
a = np.arange(10)
b = np.random.uniform(0,10)
index = np.abs(a-b).argmin()
print(a,b,index,a[index])

[0 1 2 3 4 5 6 7 8 9] 7.696657042265972 8 8


#### 15.如何找到一个数组中出现频率最高的值?
(提示: np.bincount, argmax)

In [35]:
arr = np.random.randint(0,10,20)
print(np.bincount(arr).argmax())

7


#### 16. 如何找到一个数组的第n个最大值?
(np.argsort)

In [38]:
arr = np.random.randn(20)
n = 6
print(arr[np.argsort(arr)[-n:]])

[0.53464759 0.7076599  1.00501838 1.37747163 1.37930099 1.6054516 ]


#### 17. 如何通过滑动窗口计算一个数组的平均数?
(提示 np.cumsum)

In [39]:
print(np.cumsum(arr))

[ 1.6054516   1.69670598  0.40682108 -0.42907394 -0.56069344  0.81677819
  0.7840337   0.57888817  1.58390655  1.08190685  0.8748508   1.26395701
  1.56956325  0.41464308  0.29575023  0.80686206  0.8650189   1.39966649
  2.77896747  3.48662737]


In [40]:
def slide_windows(arr,n):
    result = np.cumsum(arr,dtype = float)
    result[n:] = result[n:] - result[:-n]
    return result[n-1:] / n
a = np.arange(20)
print(slide_windows(a,3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
